# Generated by Django 5.0.3 on 2024-04-20 09:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatar',
            new_name='Avatares',
        ),
    ]
